// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdClFgyBah_4Tc8msamNjXnk2ImAL8UmI',
    appId: '1:79633479840:web:b2a1049312cdfc7f8271c5',
    messagingSenderId: '79633479840',
    projectId: 'k2help-a84da',
    authDomain: 'k2help-a84da.firebaseapp.com',
    databaseURL: 'https://k2help-a84da-default-rtdb.firebaseio.com',
    storageBucket: 'k2help-a84da.appspot.com',
    measurementId: 'G-BSDT9145HM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpfUp9GVwKUxM5L6kq-VDt32m8jwcIoVM',
    appId: '1:79633479840:android:d4c4c521a92a2f5f8271c5',
    messagingSenderId: '79633479840',
    projectId: 'k2help-a84da',
    databaseURL: 'https://k2help-a84da-default-rtdb.firebaseio.com',
    storageBucket: 'k2help-a84da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlvviCY1HG9mn63SQotPE4BN3UMgbLuiE',
    appId: '1:79633479840:ios:3c6088ee474c01828271c5',
    messagingSenderId: '79633479840',
    projectId: 'k2help-a84da',
    databaseURL: 'https://k2help-a84da-default-rtdb.firebaseio.com',
    storageBucket: 'k2help-a84da.appspot.com',
    iosBundleId: 'com.tadafuq.k2help',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlvviCY1HG9mn63SQotPE4BN3UMgbLuiE',
    appId: '1:79633479840:ios:3c6088ee474c01828271c5',
    messagingSenderId: '79633479840',
    projectId: 'k2help-a84da',
    databaseURL: 'https://k2help-a84da-default-rtdb.firebaseio.com',
    storageBucket: 'k2help-a84da.appspot.com',
    iosBundleId: 'com.tadafuq.k2help',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdClFgyBah_4Tc8msamNjXnk2ImAL8UmI',
    appId: '1:79633479840:web:5f1bae65079302488271c5',
    messagingSenderId: '79633479840',
    projectId: 'k2help-a84da',
    authDomain: 'k2help-a84da.firebaseapp.com',
    databaseURL: 'https://k2help-a84da-default-rtdb.firebaseio.com',
    storageBucket: 'k2help-a84da.appspot.com',
    measurementId: 'G-4VXFCY8BCY',
  );
}
